# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBmYEEchZBHkpzgmrtfYPGDVIQhlUc6D
"""

import dask.dataframe as dd
import pandas as pd
import numpy as np

n = 5_000_000

pdf = pd.DataFrame({
    "user_id": np.random.randint(1, 1_000_000, n),
    "category": np.random.choice(["A", "B", "C", "D"], n),
    "region": np.random.choice(["US", "EU", "ASIA"], n),
    "sales": np.random.uniform(10, 1000, n)
})

pdf.head()

ddf = dd.from_pandas(pdf, npartitions=8)
ddf

avg_sales = ddf.groupby("category")["sales"].mean()
avg_sales.compute()

total_sales = ddf.groupby("region")["sales"].sum()
total_sales.compute()

total_sales.compute().sort_values(ascending=False)